sqlite:
  :adapter: sqlite
  :dbfile: custom_field_model_plugin_test.sqlite.db
sqlite3:
  :adapter: sqlite3
  :dbfile: custom_field_model_plugin_test.sqlite3.db
mysql:
  :adapter: mysql
  :host: localhost
  :username: root
  :password:
  :database: custom_field_model_plugin_test